<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once "head.phtml" ?>
  </head>
  <body>
    <div class="grid-container">

    <div class="grid-x">
        <div class="large-2 medium-2 columns hide-for-small-only">
        <img style="padding: 10px;" src="<?php echo App::config("url") ?>public/img/Vaillant-logo.svg" alt="Logo">
        </div>
        <div class="large-10 medium-10 small-12 columns">
            <h1 style="width: 100%; text-align: center; padding-top:15px;"><?php echo App::config("nazivApp") ?></h1>
        </div>
    </div>

    <?php include_once "izbornik.phtml" ?>
       
        <div class="callout" style="min-height: 400px;">
            <?php echo $content ?>
           
        </div>
       
        <div class="callout">
           &copy; Robert Zita <?php echo date("Y") ?>
        </div>




    </div>
    
    <script src="<?php echo App::config("url") ?>public/js/vendor/jquery.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/what-input.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/app.js"></script>
  </body>
</html>