<label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Adresa
    <input type="text" name="adresa"
    value="<?php echo Request::post("adresa") ?>" />
  </label>

  <label>Poštanski broj
    <input type="number"  name="postanskibroj"
    value="<?php echo Request::post("postanskibroj") ?>" />
  </label>

  <label>Broj telefona
    <input type="text"  name="brojtelefona"
    value="<?php echo Request::post("brojtelefona") ?>" />
  </label>

  <label>Email
    <input type="text" name="email" 
    value="<?php echo Request::post("email") ?>" />
  </label>