<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>servis/edit/<?php echo Request::post("sifra") ?>">


<div class="grid-x">
<div class="large-12 columns">
        
  

  <label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label for="serviser">Serviser</label>
  <select name="serviser" id="serviser">
  <option value="0">Odaberi servisera</option>

  <?php foreach(Serviser::read(1) as $serviser): ?>

    

    <option 

      <?php if(Request::post("serviser")==$serviser->sifra):?>
      selected="selected" 
      <?php endif;?>

      value="<?php echo $serviser->sifra ?>"><?php echo $serviser->naziv ?></option>

  <?php endforeach; ?>
  </select>
  <label for="bojler">Kondenzacijski uređaj</label>
  <select name="bojler" id="bojler">
  <option value="0">Odaberi kondenzacijski uređaj</option>

  <?php foreach(Bojler::read() as $bojler): ?>

    

    <option 

      <?php if(Request::post("bojler")==$bojler->sifra):?>
      selected="selected" 
      <?php endif;?>

      value="<?php echo $bojler->sifra ?>"><?php echo $bojler->naziv ?></option>

  <?php endforeach; ?>
  </select>
  <label>Cijena
    <input type="number" name="cijena" 
    value="<?php echo Request::post("cijena") ?>" />
  </label>

  <label>Datum servisa
    <input type="date" name="datumservisa" 
    value="<?php echo date("Y-m-d",strtotime(Request::post("datumservisa"))) ?>" />
  </label>

  

  

  



  </div>
</div>
  
 <div class="grid-x">
    <div class="large-6 columns" style="padding: 10px;">
        <a href="<?php echo App::config("url") ?>servis/index" class="alert button expanded">
            Odustani
        </a>
    </div>
    <div class="large-6 columns"  style="padding: 10px;">
        <input type="submit" class="success button expanded" value="Promjeni" />
    </div>
 </div>
 

</form>
<?php echo $poruka ?>