<?php 
  $head = "<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">";

 $js="
 <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>
 <script>
 var putanja=\"" . APP::config("url") .  "\";
 let sifraServis = " . Request::post("sifra") .";
 </script>
 <script src=\"" . APP::config("url") . "public/js/servisi/edit.js\"></script>";
?>



<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>servis/edit/<?php echo Request::post("sifra") ?>">


<div class="grid-x">
<div class="large-4 columns">
        
  

  <label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  
  <label for="bojler">Kondenzacijski uređaj</label>
  <select name="bojler" id="bojler">
  <option value="0">Odaberi kondenzacijski uređaj</option>

  <?php foreach(Bojler::read() as $bojler): ?>

    

    <option 

      <?php if(Request::post("bojler")==$bojler->sifra):?>
      selected="selected" 
      <?php endif;?>

      value="<?php echo $bojler->sifra ?>"><?php echo $bojler->naziv ?></option>

  <?php endforeach; ?>
  </select>
  <label>Cijena
    <input type="number" name="cijena" 
    value="<?php echo Request::post("cijena") ?>" />
  </label>

  <label>Datum servisa
    <input type="date" name="datumservisa" 
    value="<?php if(Request::post("datumservisa")!=null){
      echo date("Y-m-d",strtotime(Request::post("datumservisa")));
    }
     ?>"/>
  </label>
  </div>
  <div class="large-1 columns">
  </div>
  <div class="large-7 columns" style="overflow: auto; max-height: 400px;">
    <div class="callout">
      traži servisera
      <input type="text" id="uvjet">
      <?php foreach(Serviser::readServisers(Request::post("serviser")) as $s): ?> 
    <span id="imeserviser" >Trenutni serviser: <?php echo $s->naziv, ", " , $s->adresa , " " , $s->postanskibroj ?></span>
    <?php endforeach;?>
    <input type="hidden" name="serviser" id="serviser" />
        </div>
    </div>      
</div>
  
 <div class="grid-x">
    <div class="large-6 columns" style="padding: 10px;">
        <a href="<?php echo App::config("url") ?>servis/index" class="alert button expanded">
            Odustani
        </a>
    </div>
    <div class="large-6 columns"  style="padding: 10px;">
        <input type="submit" class="success button expanded" value="Promjeni" />
    </div>
 </div>
 

</form>
<?php echo $poruka ?>