<?php 
  $head = "<link rel=\"stylesheet\" href=\"" . APP::config("url") . "public/css/cropper.css\">";

 $js="
  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js\"></script>
  <script src=\"https://fengyuanchen.github.io/js/common.js\"></script>
  <script src=\"" . APP::config("url") . "public/js/cropper.js\"></script>
  <script>var putanja=\"" . APP::config("url") .  "\";</script>
 <script src=\"" . APP::config("url") . "public/js/korisnici/index.js\"></script>
 
 ";
?>


<a href="<?php echo App::config("url") ?>korisnik/add" class="success button expanded">
    Dodaj novog korisnika
</a>
<div class="grid-x">
    <?php foreach($korisnici as $k): ?>
    <div class="cell large-3">
        <div class="success callout operateri">
        
            <img id="k_<?php echo $k->sifra; ?>" class="slika" src="<?php 
            
            $putanja = file_exists(App::config("path") . "public/img/korisnici/" . $k->sifra . ".png") 
            ?  App::config("url") . "public/img/korisnici/" . $k->sifra . ".png" 
            : App::config("url") . "public/img/nepoznato.png";

            echo $putanja ?>" alt="" />
            <h1><?php echo $k->ime?>
    <br />
    <?php echo $k->prezime?>
    </h1>
    <?php echo $k->email?>
    <hr />
    <a href="<?php echo App::config("url") ?>korisnik/prepareedit/<?php echo $k->sifra ?>">
        <i class="fas fa-edit fa-2x"></i>
    </a>

    <?php if($k->ukupno==0): ?>
        <a style="color: red;"
            href="<?php echo App::config("url") ?>korisnik/delete/<?php echo $k->sifra ?>">
            <i class="fas fa-trash fa-2x"></i>
        </a>
    <?php endif; ?>

    </div>
    </div>

    <?php endforeach; ?>
</div>

<div class="reveal" id="slikaModal" data-reveal>
  <img id="image" src="" alt="" />
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremi">Spremi</a>

  <button class="close-button" data-close aria-label="Close reveal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
