<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>bojler/edit/<?php echo Request::post("sifra") ?>">


<div class="grid-x">
<div class="large-12 columns">
        
  

  <label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Učinak na grijanju
    <input type="number" name="ucinaknagrijanju" 
    value="<?php echo Request::post("ucinaknagrijanju") ?>" />
  </label>
  
  <label>Učinak na toploj vodi
    <input type="number" name="ucinaknatoplojvodi" 
    value="<?php echo Request::post("ucinaknatoplojvodi") ?>" />
  </label>

  <label for="korisnik">Korisnik</label>
  <select name="korisnik" id="korisnik">
  <option value="0">Odaberi korisnika</option>

  <?php foreach(Korisnik::read() as $korisnik): ?>

    

    <option 

      <?php if(Request::post("korisnik")==$korisnik->sifra):?>
      selected="selected" 
      <?php endif;?>

      value="<?php echo $korisnik->sifra ?>"><?php echo $korisnik->ime ?> <?php echo $korisnik->prezime ?></option>

  <?php endforeach; ?>

  </select>



  </div>
</div>
  
 <div class="grid-x">
    <div class="large-6 columns" style="padding: 10px;">
        <a href="<?php echo App::config("url") ?>bojler/index" class="alert button expanded">
            Odustani
        </a>
    </div>
    <div class="large-6 columns"  style="padding: 10px;">
        <input type="submit" class="success button expanded" value="Promjeni" />
    </div>
 </div>
 

</form>
<?php echo $poruka ?>